### ISSUE TITLE
Showing metadata loses your place on the page and interrupts video

### ISSUE THREAD

**Issue by markplindsay2** [xiaofei-mo/mysteriousobjectsatnoon#1]
> Currently, showing metadata loses your place on the page and interrupts video — should be able to show/hide metadata without interrupting video playback or moving layout position.

**Comment by markplindsay** [comment]
Xiaofei, this should be fixed. Videos are still being unloaded while scrolling back and forth to get around browsers' connection limit. However, when each video is unloaded, the video component saves its place so it can resume the video in the same place when it is loaded again. Also, metadata should be editable even if a video is in an unloaded state.

**Comment by markplindsay** [comment]
Let's use https://github.com/xiaofei-mo/mysteriousobjectsatnoon/issues/3 for this since it is a similar issue.
