### ISSUE TITLE
Change order of metadata fields

### ISSUE THREAD

**Issue by markplindsay** [xiaofei-mo/mysteriousobjectsatnoon#8]
> Please list the following fields in order:
> Title, Year, Duration (auto-generated), Color (auto-generated), Rhythm (auto-generated), Things, Textures, Forms, Movements, Emotions, Concepts, Others, Source, Copyright (drop-down)

**Comment by markplindsay2** [comment]
According to Wireframe 1106_OLDMENU4MARK:

> Title, Year, Duration, Color, Rhythm, Things, Textures, Forms, Movements, Emotions, Concepts, Source, Other

**Comment by markplindsay** [comment]
Ordering from `Wireframe 1106_OLDMENU4MARK.pdf`:

> Title, Year, Duration, Color, Rhythm, Things, Textures, Forms, Movements, Emotions, Concepts, Source, Other

Reordered and added all fields except for Color and Rhythm pending answer on auto-generating these values.
